### ISSUE TITLE
User defined datasets documentation

### ISSUE THREAD

**Issue by arquicanedo** [Sujit-O/pykg2vec#10]
Perhaps we should add a short paragraph about adding user-defined datasets.

**Comment by louisccc** [comment]
Allowing a user to use custom dataset by assigning the path parameter (-cd /dataset/userdefineddataset) might be a better option. In this way, a user can avoid changing the library to apply custom dataset.

**Comment by arquicanedo** [comment]
Yes, that's probably a better option. This way the user data set can be anywhere in in the file system and not restricted to the dataset directory.

**Comment by louisccc** [comment]
will finish this in #12 .

**Comment by Sujit-O** [comment]
handled in #12
