### ISSUE TITLE
connection.py line 393

### ISSUE THREAD

**Issue by arquicanedo** [Sujit-O/pykg2vec#11]
I got this error on my custom dataset.

iter[0] ---Train Loss: 549108.26129 ---time: 2612.50
Testing [992/391166] Triples
Inferring for Evaluation: | Done:100% Time:  0:01:38                                                  
Traceback (most recent call last):
  File "/Users/canedo/anaconda3/envs/pykg2vec/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/Users/canedo/anaconda3/envs/pykg2vec/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Users/canedo/anaconda3/envs/pykg2vec/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by Sujit-O** [comment]
This is due to the limitation of the queue size during evaluation. We were planning to address this by creating a chunk of the evaluation data rather than trying to store everything in one queue. Will update it soon.

**Comment by arquicanedo** [comment]
Great. I look forward for the update. My dataset doest not conclude as it hangs in this error message. I tried an explicit cast of "n" as an int, but that doesn't seem to solve the problem.

**Comment by Sujit-O** [comment]
I have fixed this issue. The evaluator should now be able to handle large test triple size with no issue. Although, currently for testing 50,000 triples, it takes around 804 seconds in my MacBook Pro with a single process. Will reduce it by increasing the number of processes for the evaluation later.
