### ISSUE TITLE
Output the predictions in human-readable form

### ISSUE THREAD

**Issue by aaksakal** [Sujit-O/pykg2vec#14]

**Comment by Sujit-O** [comment]
Could you elaborate on the issue further? Which output prediction are we talking about, and what form are you expecting?

**Comment by louisccc** [comment]
@Sujit-O, I think Ahmet was meant to say something like this: 

 idx | Triple | Missing Tail or Head?(T/H) | Predictions
-- | -- | -- | --
0 | <pix2pix/conv2d_9>, <has_kernel_size>, <(3,3)> : | T | ['(3,3)']
