### ISSUE TITLE
Implementation: SimplE

### ISSUE THREAD

**Issue by baxtree** [Sujit-O/pykg2vec#140]
Paper reference: https://papers.nips.cc/paper/7682-simple-embedding-for-link-prediction-in-knowledge-graphs

Implementation reference: [SimplE_avg](https://github.com/Mehran-k/SimplE/blob/master/simplE_avg.py) and [SimplE_ignr](https://github.com/Mehran-k/SimplE/blob/master/simplE_ignr.py)

**Comment by louisccc** [comment]
Finished in #141
