### ISSUE TITLE
SystemExit: 2

### ISSUE THREAD

**Issue by tobimichigan** [Sujit-O/pykg2vec#145]
## Issue Template
First of all, thank you for finding the bugs. Please help us improve by providing the bug report as much as possible in the following format.

**Describe the bug**
/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
usage: ipykernel_launcher.py [-h] [-th TRAINING_THRESHOLD] [-nc NCLUSTER]
                             [-crp CRP_FACTOR] [-stb STEP_BEFORE]
                             [-wn WEIGHT_NORM] [-func FUNCTION] [-cmax CMAX]
                             [-cmin CMIN] [-fmd FEATURE_MAP_DROPOUT]
                             [-idt INPUT_DROPOUT] [-hdt HIDDEN_DROPOUT]
                             [-lbs LABEL_SMOOTHING]
                             [-fsize FILTER_SIZES [FILTER_SIZES ...]]
                             [-fnum NUM_FILTERS] [-al ALPHA] [-lmda LMBDA]
                             [-b BATCH_TRAINING] [-mg MARGIN] [-opt OPTIMIZER]
                             [-s SAMPLING] [-ngr NEGRATE] [-l EPOCHS]
                             [-lr LEARNING_RATE] [-k HIDDEN_SIZE]
                             [-km ENT_HIDDEN_SIZE] [-kr REL_HIDDEN_SIZE]
                             [-k2 HIDDEN_SIZE_1] [-l1 L1_FLAG] [-gp GPU_FRAC]
                             [-npg NUM_PROCESS_GEN] [-mn MODEL_NAME]
                             [-db DEBUG] [-exp EXP] [-ds DATASET_NAME]
                             [-dsp DATASET_PATH] [-ld LOAD_FROM_DATA]
                             [-sv SAVE_MODEL] [-tn TEST_NUM] [-ts TEST_STEP]
                             [-t TMP] [-r RESULT] [-fig FIGURES]
                             [-plote PLOT_EMBEDDING] [-plot PLOT_ENTITY_ONLY]
ipykernel_launcher.py: error: ambiguous option: -f could match -func, -fmd, -fsize, -fnum, -fig

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**To Reproduce**
`# Author: Sujit Rokka Chhetri
# License: MIT

import sys

from pykg2vec.utils.kgcontroller import KnowledgeGraph
from pykg2vec.config.config import Importer, KGEArgParser
from pykg2vec.utils.trainer import Trainer

def main():
    # getting the customized configurations from the command-line arguments.
    args = KGEArgParser().get_args(sys.argv[1:])

    # Preparing data and cache the data for later usage
    knowledge_graph = KnowledgeGraph(dataset=args.dataset_name, negative_sample=args.sampling)
    knowledge_graph.prepare_data()

    # Extracting the corresponding model config and definition from Importer().
    config_def, model_def = Importer().import_model_config(args.model_name.lower())
    config = config_def(args=args)
    model = model_def(config)

    # Create, Compile and Train the model. While training, several evaluation will be performed.
    trainer = Trainer(model=model, debug=args.debug)
    trainer.build_model()
    trainer.train_model()

if __name__ == "__main__":
    main()`

**Expected behavior**
Flawless run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux
 - SDK: jupyter notebook

**Dependency (please complete the following information):**
 - Current version of the dependencies

**Additional context**
Is anyone still monitoring this repo?

**Comment by louisccc** [comment]
Yes there is someone still monitor this repo. 
But from this report, I can't tell what's happening in your environment. Can you report more information so that I can help?

**Comment by tobimichigan** [comment]
Thanks for your reply @louisccc , the jupyter notebook snippet is not running as expected. Perhaps the code is deprecated.

**Comment by louisccc** [comment]
related to #144 .
