### ISSUE TITLE
Improve the ghd argument usage

### ISSUE THREAD

**Issue by louisccc** [Sujit-O/pykg2vec#163]
1) redundant definition under root/pykg2vec and root/examples. 
2) should supports users to specify custom definitions of optimizing search space. like -ghd my_search_space.yaml.

**Comment by baxtree** [comment]
PR #166 allows the user to pass in a single hyperparameter file and the files in the example folder are reduced.

`python train.py -exp True -mn TransE -ds fb15k -hpf ./examples/hyperparams/custom.yaml`

I can see another ongoing PR is targeting separating out the configuration on search space so please consider rebasing.

**Comment by louisccc** [comment]
rebased finished. close issue.
