### ISSUE TITLE
how do i run this? both the documentation and example in git give different codes.

### ISSUE THREAD

**Issue by sunil747** [Sujit-O/pykg2vec#167]
## 'NoneType' object has no attribute 'outputs' in trainer.build_model()

**This is the code so far**

    import sys
    
    
    #from pykg2vec.data.kgcontroller import KnowledgeGraph
    from pykg2vec.utils.kgcontroller import KnowledgeGraph
    
    from pykg2vec.config.config import Importer, KGEArgParser
    #from pykg2vec.common import Importer, KGEArgParser
    from pykg2vec.utils.trainer import Trainer
    
    
    def main():
        # getting the customized configurations from the command-line arguments.
        args = KGEArgParser().get_args(sys.argv[1:])
    
        # Preparing data and cache the data for later usage
        #knowledge_graph = KnowledgeGraph(dataset=args.dataset_name, custom_dataset_path=args.dataset_path)
        
        knowledge_graph = KnowledgeGraph(dataset=args.dataset_name, negative_sample=args.sampling)
        
        knowledge_graph.prepare_data()
        
        
        
        
    
        # Extracting the corresponding model config and definition from Importer().
        config_def, model_def = Importer().import_model_config(args.model_name.lower())
        
        print('-----------------------------------')
        print(model_def)
        print(config_def)
        print('-----------------------------------')
        
        
        config = config_def(args=args)
        
        print(config)
        
        ####model = model_def(**config.__dict__)
        model = model_def(config)
        
        print(model)
        
        print('model done')
    
        #### Create, Compile and Train the model. While training, several evaluation will be performed.
        #trainer = Trainer(model=model, debug=True)
        #trainer = Trainer(model, config)
        trainer  = Trainer(model=model,debug=args.debug)
    
        trainer.build_model()
        trainer.train_model()
    
    
    if __name__ == "__main__":
        main()

**I run it with arguments as follows**

-mn TransE -ds fb15k

**Comment by louisccc** [comment]
Hello, sunil

yea previously the code in user document is kind of inconsistent with the repo. However, right now we have made them synced. 
Can you try the one shown here again? https://pykg2vec.readthedocs.io/en/latest/auto_examples/train.html

Thanks!

**Comment by sunil747** [comment]
thank you it ran but I see no figures generated
