### ISSUE TITLE
No golden hyper-parameter developed for TuckER

### ISSUE THREAD

**Issue by ArkDu** [Sujit-O/pykg2vec#181]
No yaml file included for model TuckER in hyperparams folder

**Comment by baxtree** [comment]
Golden Parameters and search spaces were added by https://github.com/Sujit-O/pykg2vec/pull/184.

**Comment by baxtree** [comment]
Hi, @ArkDu, could you verify if this issue has been resolved?

**Comment by ArkDu** [comment]
Yes the issue has been resolved.
