### ISSUE TITLE
Changing hyperparameters when training on custom dataset

### ISSUE THREAD

**Issue by Bhaskarkvvsr** [Sujit-O/pykg2vec#192]
When I was trying to train a TransE model on the custom dataset its taking a while as the dataset is huge(3M triplets). Then I tried to change the default value of epochs from 100 to 3 in pykg2vec.common.py file. But still it's value is showing as 100 while training. How to change the hyperparemeters when training on the custom dataset?

**Comment by Bhaskarkvvsr** [comment]
I found the solution

**Comment by shivanisrivarshini** [comment]
Can you please provide solution
