### ISSUE TITLE
display and save the summary of the data-set during training/testing

### ISSUE THREAD

**Issue by Sujit-O** [Sujit-O/pykg2vec#24]
As an enhancement, it would nice to see the summary of the dataset such as total triples, total entities, total relations, etc. displayed during training and saved afterward.

**Comment by louisccc** [comment]
1) for display, are you saying we should print it per training epoch or per tiny testing? 
2) for saving afterward, I believe we already save pickled KGMetaData structure along with the dataset (e.g. metadata.pkl). are you saying we should save it in text format?

**Comment by louisccc** [comment]
done
