### ISSUE TITLE
SME test_batch function

### ISSUE THREAD

**Issue by aaksakal** [Sujit-O/pykg2vec#4]
While training SME there is a bug. When followed it leads to the test_batch method of SME class. It only has a pass. However, Evaluator is using that function. 

https://github.com/Sujit-O/pykg2vec/blob/88b7fc8f24f8049d1921ded141c8d533c939e56f/pykg2vec/core/SME.py#L135-L136

The screenshot of the error: 

![image](https://user-images.githubusercontent.com/44760682/57907292-de4f9980-7831-11e9-88d0-36459b8b76c8.png)

**Comment by Sujit-O** [comment]
Added the test_batch function for both linear and bilinear models.
