### ISSUE TITLE
ConvE performance issue

### ISSUE THREAD

**Issue by saatviga-healx** [Sujit-O/pykg2vec#50]
Hi,
Training the ConvE model with the given default parameters does not learn even after several epochs. Have you seen good performance with this model?

**Comment by Sujit-O** [comment]
Hi Saatviga, could you post the ranks and hit ratios that you received while running ConvE?

**Comment by saatviga-healx** [comment]
Hi Sujit,

All I got was 0.000 scores for both mean rank and hits ratios even after
many epochs with ConvE.
The same command was working for TransE and ProjE_pointwise which I also
tried using.


Regards
Saatviga

**Comment by louisccc** [comment]
already handled in 0.0.47.
