### ISSUE TITLE
Add link to preprint in readme

### ISSUE THREAD

**Issue by impredicative** [Sujit-O/pykg2vec#51]
I see that the readme of this repo mentions the associated title under the Cite section: "pykg2vec: Python Knowledge Graph Embedding Library". Please also consider adding a link to the corresponding preprint on Arxiv: https://arxiv.org/abs/1906.04239

Having this link in the readme will be useful for reference purposes. Thanks.

**Comment by Sujit-O** [comment]
Thank you for catching this. We have updated the readme.
