### ISSUE TITLE
support inference method for all models

### ISSUE THREAD

**Issue by wujunzhuo** [Sujit-O/pykg2vec#59]
```python
tail = model.inference(h=10, r=20)
# e.g., TransE model returns the sum vector: head + rel
```

**Comment by louisccc** [comment]
@wujunzhuo 
Hello @wujunzhuo, I have an update related to the inference feature you requested in the development branch. Can you kindly try the [example/inference.py](https://github.com/Sujit-O/pykg2vec/blob/development/pykg2vec/example/inference.py) and see if it fits what you want?
