### ISSUE TITLE
About  Format of User Defined Dataset

### ISSUE THREAD

**Issue by NerdTsai** [Sujit-O/pykg2vec#60]
### About  Format of User Defined Dataset
I'm  trying to reproduce the NTN model, using pykg2vec. I noticed issue#12, your team have done the user defined dataset using parameter, but I don't think it's detailed enough let me using it, Could you show more about format of dataset ,pls.

### Bug Tips
Something wrong with README.md,
​```
python train.py -m TransE # Run TransE model.
​```
should be
​```
python train.py -mn TransE # Run TransE model.
​```

**Comment by Sujit-O** [comment]
fixed the bug in the readme.
