### ISSUE TITLE
Export embedding table

### ISSUE THREAD

**Issue by aabccd021** [Sujit-O/pykg2vec#69]
I'm trying to get embedding table (entity_name, embedding_representation_vector), but no good for now.

I used sample code in readme to embed Freebase15K and I tried to pickle dump the model and the trainer, but error occurs : `TypeError: can't pickle _thread.RLock objects`. I'm new to tensorflow and haven't found good solution for this.

Can I export the model to be used for transfer training?
How can I export the entity embedding table to json or csv?

**Comment by Sujit-O** [comment]
Currently, there is an option to save the  self.parameter_list which consists of the entity and relation embedding, along with some model parameters such as bias or conversion matrix.  
the current architecture uses tf.train.Saver to save these parameters as shown below.

saver = tf.train.Saver(self.model.parameter_list)
saver.save(self.sess, str(saved_path / 'model.vec'))

Please check https://www.tensorflow.org/api_docs/python/tf/train/Saver to learn more about how the models and the parameters are saved in Tensorflow. 

currently, we do not have a support for saving the embeddings and model parameters in json or csv. However, if you want to do it, you should go inside the tensorflow session in the trainer and save the values by utilizing sess.run() to acquire the embedding, model parameters, and so on and save it in the format you desire before closing the sesssion.

The easy solution would be to utilize the tf.train.saver() to store and retrieve the model parameters for the purpose of transfer learning. These paramters can be saved and restored to initialize the next model for transfer learning purpose.

**Comment by aabccd021** [comment]
Thank you for the answer.
