### ISSUE TITLE
deprecate warning

### ISSUE THREAD

**Issue by YvonneChe** [Sujit-O/pykg2vec#75]
**Describe the bug**
to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead

(from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

**To Reproduce**
1. run "kg_pipeline.tune()"
2. See warning

**Comment by louisccc** [comment]
this should be fixed in #114.
