### ISSUE TITLE
"KG2E" object has no attribute 'ent_embeddings'

### ISSUE THREAD

**Issue by aungthu17593** [Sujit-O/pykg2vec#76]
**Describe the bug**
"KG2E" object has no attribute, 'ent_mebeddings'

**To Reproduce**
Run train.py with kg2e as model.

**Expected behavior**
After training, the trainer tries to visualize kg2e embeddings. There is an error in initialization of Visualization class because kg2e has no ent/rel embeddings.

**Screenshots**
![image](https://user-images.githubusercontent.com/32527287/63301707-11ba1e00-c290-11e9-90fc-a8961faa7690.png)

**Comment by louisccc** [comment]
we don't have a good way to visualize kg2e's embeddings so we will disable the plotting of the embeddings generated from this algorithm.
