### ISSUE TITLE
ConvKB training

### ISSUE THREAD

**Issue by saatviga-healx** [Sujit-O/pykg2vec#77]

**Comment by saatviga-healx** [comment]
Describe the bug
Thanks for the ConvKB implementation but I have a confusion since ConvE and ConvKB training functions look similar. 

To Reproduce

Expected behavior
In ConvKB (h,r,t) should be stacked and passed to convolution layers instead of h,r at a time. Can you please clarify?

**Comment by louisccc** [comment]
should be fixed in #114 .
