### ISSUE TITLE
Stopped running at epoch 162

### ISSUE THREAD

**Issue by trbn** [Sujit-O/pykg2vec#78]
Many thanks for your great library.

In fact, I have run TransE model on my custom dataset. Every things were ok for 100 epochs. But when I run it for 1000 epochs, the system stop at epoch 162 and don't go forward. At first, I thought it is related to low RAM but it was not. I use a GPU with 22G RAM and at epoch 162, 13G is free.

I have attached the state of running.
![error](https://user-images.githubusercontent.com/4402502/64331964-f6b61080-cfe8-11e9-8759-4bdce51369ce.jpg)

**Comment by louisccc** [comment]
Hello, can you provide more information like what are config parameters for your trial? Only with this information then I can try to analyze or reproduce the issue in my local environment.

**Comment by trbn** [comment]
Hi Louisccc,
This configs:
config.epochs = 1000
config.test_step = 1
config.test_num = 1
config.disp_result = True
config.save_model = False

Do you need my custom dataset too?

**Comment by louisccc** [comment]
This is because of the slow testing in the background process.  so your training was actually finished. pykg2vec was just trying to finish the remaining evaluations in background!
