### ISSUE TITLE
cannot import name 'KnowledgeGraph'

### ISSUE THREAD

**Issue by iamlxb3** [Sujit-O/pykg2vec#79]
When I run the train.py example:

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from pykg2vec.config.global_config import KnowledgeGraph
ImportError: cannot import name 'KnowledgeGraph'

**Comment by kaihuchen** [comment]
@iamlxb3 FYI, I got the same error, but managed to get it going with the following changes:

Change from:

from pykg2vec.config.global_config import KnowledgeGraph
    # ...
    args = KGEArgParser().get_args()

To:

from pykg2vec.utils.kgcontroller import KnowledgeGraph
    # ...
    args = KGEArgParser().get_args([])

**Comment by louisccc** [comment]
Hi @kaihuchen, you are right, thanks for pointing out! :)
