### ISSUE TITLE
Documentation for user defined dataset?

### ISSUE THREAD

**Issue by vishalmhjn** [Sujit-O/pykg2vec#91]
What should be the format of the user/ custom dataset?

**Comment by baxtree** [comment]
You can pass in the path to the user defined dataset when creating a knowledge graph. For example,

https://github.com/Sujit-O/pykg2vec/blob/e31897c94025eb1df88c9f89c343f25587e6ba51/pykg2vec/test/test_kg.py#L66

The `custom_dateset_path` is basically pointed to a folder containing your test, train and valid triple files. For example, this is a dummy custom dataset:

https://github.com/Sujit-O/pykg2vec/tree/development/pykg2vec/test/resource/custom_dataset

**Comment by louisccc** [comment]
Hey @vishalmhjn, you can actually find the description here:
https://github.com/Sujit-O/pykg2vec#using-custom-dataset

Nevertheless, I will update the description of this part to make it look better and descriptive.

**Comment by louisccc** [comment]
readme updated
